/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hungvk.demo.annotation;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
    }
}
